### ISSUE TITLE
Handle InfoWindow tapped event

### ISSUE THREAD

**Issue by HelenGuov** [apptreesoftware/flutter_google_map_view#10]
We have found that your current library doesn't handle InfoWindow tapped event, and we need it for our app. Therefore, I have decided to change the add this functionality to your library. Is it ok to do a pull request?

**Comment by johnpryan** [comment]
Yes feel free to make a pull request

**Comment by matthewtsmith** [comment]
https://github.com/apptreesoftware/flutter_google_map_view/pull/11 merged
