### ISSUE TITLE
indoor_building.dart missing

### ISSUE THREAD

**Issue by LJaraCastillo** [apptreesoftware/flutter_google_map_view#100]
Said file is missing in #95 PR and now is creating conflict when building the plugin or projects using the plugin. @KoheiKanagu  please commit the missing file.

**Comment by KoheiKanagu** [comment]
@LJaraCastillo 

Thank you for reporting.
I created new pull request #101

**Comment by LJaraCastillo** [comment]
No problem.
If this was solved i will close this issue.
