### ISSUE TITLE
i can't add other widget to mapView

### ISSUE THREAD

**Issue by nattaaek** [apptreesoftware/flutter_google_map_view#106]
mapView always on top 
https://imgur.com/a/JqErzcs

Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      bottomNavigationBar: BottomNavigationBar(
          currentIndex: 0,
          items: [
            BottomNavigationBarItem(
              icon: new Icon(Icons.book),
              title: new Text('Map'),
            ),
            BottomNavigationBarItem(
              icon: new Icon(Icons.info),
              title: new Text('Reservation info')
          )
        ],
      ),
      body: showMap(),
    );

it's doesn't show any AppBar and buttonNavigation

**Comment by johnpryan** [comment]
This is a full-screen plugin. For inline-maps you can consider using package:flutter_map instead
