### ISSUE TITLE
Can you support encoded polyline from Google Maps?

### ISSUE THREAD

**Issue by zackszhu** [apptreesoftware/flutter_google_map_view#112]
Thank you for this awesome widget.

I am currently working on a project which requires to draw polylines from Google Maps encoded polyline. The detailed documentation of it is here: [link](https://developers.google.com/maps/documentation/utilities/polylinealgorithm). I was wondering if you can support this kind of data format?

Thanks!

**Comment by matthewtsmith** [comment]
@zackszhu This plugin already supports providing points to make a polyline. You should be able to decode the polyline from google and pass that into the MapView. I believe there are quite a few examples out there on how to decode the polylines.
