### ISSUE TITLE
Can not display the map , there is only a Cat with flower

### ISSUE THREAD

**Issue by carlosbdw** [apptreesoftware/flutter_google_map_view#113]
I could see the Google logo ,but no map there.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v0.5.8, on Mac OS X 10.13.6 17G65)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.6)
[✓] Connected devices (2 available)

**Comment by matthewtsmith** [comment]
This typically indicates you did not add an API key properly. Please see the example and the README for how to get an API key.
