### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by hojabbr** [apptreesoftware/flutter_google_map_view#117]
Flutter is fairly new, and the majority of people coming on board have no clue what is going on (including myself), can you please put a very simple example of just showing a map inside a perhaps `Container` with some sample coordinates?

Thank you

**Comment by stafyniaksacha** [comment]
+1

**Comment by matthewtsmith** [comment]
This package is deprecated. See the [Readme](https://github.com/apptreesoftware/flutter_google_map_view/blob/master/README.md).

We suggest you now use the [official google maps plugin](pub.dartlang.org/packages/google_maps_flutter) from the flutter team.
