### ISSUE TITLE
can't go back to previous view

### ISSUE THREAD

**Issue by superciccio** [apptreesoftware/flutter_google_map_view#12]
the close button seems not to work properly.. i tried to use WillPopScope nothing either

**Comment by matthewtsmith** [comment]
Can you provide more info or show me an example of what your code is trying to do.

**Comment by matthewtsmith** [comment]
Closing. Please re-open if you have an example we can work through. If you follow the example app for the plugin you can see how close the map when you tap a toolbar item.
