### ISSUE TITLE
iOS Permission not requested

### ISSUE THREAD

**Issue by quintusvw** [apptreesoftware/flutter_google_map_view#18]
First of all thank you for this plugin!

I can successfully use the location updates on an Android device since it asks for permission to access my location.

On my iOS device it never asks for the permission, so I assume it does not have permission to access my location, and my app does not even list under the Location Services settings of iOS. I'm not sure if this is a problem on Flutter's side of the map_view.

I did add the following in my Info.plist:

<key>NSLocationWhenInUseUsageDescription</key>
<string>Using location to display on a map</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>Using location to display on a map</string>

Please assist.

**Comment by nunorpg** [comment]
I recently came across the same issue, did you find any solution?

**Comment by PenguinGovernor** [comment]
Having the same issue, works on Android just fine.

Any solution would be cool!

**Comment by quintusvw** [comment]
I'm sorry, but I have not found any solution that I can recommend. I was hoping that this issue would be resolve by now, unless there might be another problem that is causing this to happen (perhaps something unrelated).
