### ISSUE TITLE
**BUILD FAIL** IN ANDROID

### ISSUE THREAD

**Issue by KeshavAdityaRP** [apptreesoftware/flutter_google_map_view#26]
When I run **flutter run** :

Launching lib/main.dart on Moto G 5 Plus in debug mode...
Initializing gradle...                                       0.8s
Resolving dependencies...
* Error running Gradle:
Exit code 1 from: /home/keshav/Projects/Flutter Projects/map_snippet/android/gradlew app:properties:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/keshav/Projects/Flutter Projects/map_snippet/android/build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > org.xml.sax.SAXParseException; systemId: file:/home/keshav/Projects/Flutter%20Projects/map_snippet/android/app/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 74; The prefix "android" for attribute "android:name" associated with an element type "uses-permission" is not bound.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Please review your Gradle project setup in the android/ folder.

This is how my what my **pubspec.yml** has :

    dependencies:
      flutter:
        sdk: flutter
      cupertino_icons: ^0.1.0
      map_view: ^0.0.10
      matcher: '>=0.12.0 <0.13.0'
      utf: '>=0.8.10 <=0.10.0'
      quiver: '>=0.17.0 <=0.26.2'
    
    dev_dependencies:
      test: '>=0.12.0 <=0.13.0'

**Comment by matthewtsmith** [comment]
Looking at the output error:

file:/home/keshav/Projects/Flutter%20Projects/map_snippet/android/app/src/main/AndroidManifest.xml; lineNumber: 1; columnNumber: 74; The prefix "android" for attribute "android:name" 

It looks like you put the uses-permission in the wrong spot. You can refer to the example project to see where the uses-permission belongs.
