### ISSUE TITLE
How to find current location of the user using map_view in flutter?

### ISSUE THREAD

**Issue by KeshavAdityaRP** [apptreesoftware/flutter_google_map_view#28]
I would like to set initialCameraPosition to point to the user's current position rather than hard code a longitude and latitude.

```
  showMap() {
     mapView.show(
      new MapOptions(
          mapViewType: MapViewType.normal,
          showUserLocation: true,
          initialCameraPosition: new CameraPosition(
              new Location(23.2599, 77.4126), 10.0),
          title: "Parking Spaces"),
      toolbarActions: [new ToolbarAction("Close", 1)]
      );
```

**Comment by matthewtsmith** [comment]
You can use `mapView.onLocationUpdated`. 

`mapView.onLocationUpdated.listen((location) => myUserLocation = location);`

**Comment by relativityboy** [comment]
@matthewtsmith - As of this writing **flutter_google_map_view** (this lib is) deprecated, but it's worth noting that a complete version of the above

```
mapView.onLocationUpdated
        .listen((Location location) {
        mapView.setCameraPosition(new CameraPosition(location, 10.0));
    });
```

Will keep updating the map's location.
