### ISSUE TITLE
How do I remove the appBar ?

### ISSUE THREAD

**Issue by xlreon** [apptreesoftware/flutter_google_map_view#29]
I am trying to use the map for full display and I do not want the white app bar that comes in the top.
How to remove it?

**Comment by matthewtsmith** [comment]
That is currently not supported. If you wanted to submit a PR, the best way to do this would probably be to add a new MapOption for `showFullscreen`. On iOS you could hide the UINavigationControllers navBar and on Android you could set it to a titleless window.

**Comment by xlreon** [comment]
Okay, sure I will try to do it.
