### ISSUE TITLE
Exception: HTTP request failed, statusCode: 403

### ISSUE THREAD

**Issue by nunorpg** [apptreesoftware/flutter_google_map_view#30]
I've downloaded the example project folder but I wasn't able to make it work (both on android and iOS)..
The project compiles without errors and the application launches as expected but the map won't show, and an exception for the http request is thrown with statusCode 403.
I'm using an unrestricted API key, and I'm certain it works, cause I've tested it on another Android project and the map is loaded.

**Comment by matthewtsmith** [comment]
That typically means that the API key is not set. You need to do that view the MapView API. For running on Android, you also have to add the API key to the AndroidManifest.xml

**Comment by nunorpg** [comment]
Thanks for the quick response, my problem was that I didn't enable "Google Static Maps API". You should add that to the readme cause it's only on the code.

**Comment by zsyphon** [comment]
Has anyone found a work around? The example works for me sometimes and sometimes not.

Most of the time I get the 403 when it request the static map.

Here's my flutter info:
[✓] Flutter (Channel master, v0.10.2-pre.99, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 0.10.2-pre.99 at /Users/jchasecrafton/flutter
    • Framework revision c319b890b3 (13 days ago), 2018-10-29 19:44:36 -0700
    • Engine revision 162b2e98c0
    • Dart version 2.1.0 (build 2.1.0-dev.8.0 bf26f760b1)
