### ISSUE TITLE
Numbered map pins

### ISSUE THREAD

**Issue by myleftshoe** [apptreesoftware/flutter_google_map_view#33]
Thanks for this lib! Is there any way to have numbered map pins for easy identification? I'll typically be showing 30 - 60 pins at a time

**Comment by matthewtsmith** [comment]
@myleftshoe We do not plan on adding a lot of features to this plugin. Our development efforts are focused on https://github.com/apptreesoftware/flutter_map which would allow you to place any Widget on a map. This approach would let you cluster items.
