### ISSUE TITLE
Creating AlertDialog inside mapView

### ISSUE THREAD

**Issue by nunorpg** [apptreesoftware/flutter_google_map_view#35]
Hello,

I'm trying to create an AlertDialog when the a marker annotation is tapped, but I'm failing to do so.
I think the problem is related with the 'context' available on flutter (needed from 'showDialog()').
Is there any way of getting the mapView context on flutter? 
Or do I have to create a pipe for iOS and Android to handle this matter? 

Best Regards

**Comment by rajeshzmoke** [comment]
+1

**Comment by johnpryan** [comment]
Flutter AlertDialogs won't be displayed because those dialogs are drawn on the flutter view. I think the best way do display a dialog would be to close the google map view and then display the dialog

**Comment by rogeliotrejo13** [comment]
I have same problem, any idea?
