### ISSUE TITLE
License for this library

### ISSUE THREAD

**Issue by bbailleux** [apptreesoftware/flutter_google_map_view#36]
Hello dear author,
in order to use flutter_google_map_view component, it is important to know its license to avoid any legal risk.
Can you add at least the name of the chosen license in the LICENSE file ?

**Comment by cavedweller** [comment]
This is also something I care about. I'd like to suggest BSD 3-clause, MIT, or Apache 2.0.

**Comment by matthewtsmith** [comment]
Added MIT license
