### ISSUE TITLE
Help troubleshooting on iOS

### ISSUE THREAD

**Issue by dragonfax** [apptreesoftware/flutter_google_map_view#4]
I can't build on android because of an error, but I can get a successful build on iOS.

When I start it up in the iOS emulator, I can open a map_view, it shows the tab bar and I can even close and dismiss it.

But It never loads a map. It just shows a white screen, with the tab-bar at the top (and associated close button). No map.

I followed the setup instructions, including the Info.plist, and the map api key.

**Comment by matthewtsmith** [comment]
That sounds like your map API key is not setup correctly. For iOS, you have to have a map key with the iOS bundle ID registered to that API key. See instructions here: https://developers.google.com/maps/documentation/ios-sdk/get-api-key. Specifically the steps under `Detailed guide for users of the standard Google Maps SDK for iOS`

**Comment by dragonfax** [comment]
Yeah, that was it. Had Javascript Maps API enabled, but not the Android and iOS ones.
