### ISSUE TITLE
Additional changes required for android

### ISSUE THREAD

**Issue by dragonfax** [apptreesoftware/flutter_google_map_view#5]
In addition to installing NDK bundle, these are the other changes I had to make to my project for map_view to work on Android.

`android/build.gradle` needed

```
buildscript
  dependencies
    classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.2-4'
```

`AndroidManifest.xml` needed

`        <activity android:name="com.apptreesoftware.mapview.MapActivity" android:theme="@style/Theme.AppCompat.Light.DarkActionBar"/>`

**Comment by dragonfax** [comment]
Without these I get a 'no kotlin plugin' error during build, and a runtime error when I try to use the map_view api, about missing activity from the manifest.

**Comment by matthewtsmith** [comment]
Thanks for investigating. I should be able to get to updating our README.md tonight. Also, feel free to make a PR for these changes if you're up for it.

**Comment by dragonfax** [comment]
BTW, the map is working great.

**Comment by matthewtsmith** [comment]
I've updated the documentation to reflect these items.
