### ISSUE TITLE
Plans to bring in polygon support?

### ISSUE THREAD

**Issue by nikhildev** [apptreesoftware/flutter_google_map_view#51]
Its great that you have support for polyline. Do you have plans to support polygons as well(https://developers.google.com/maps/documentation/javascript/examples/polygon-simple)?

My team could really benefit from it. On a more positive note, I think I should contribute to it 😉

**Comment by johnpryan** [comment]
If you have experience with the API, feel free to contribute - we are happy to answer any questions you have about contributing

**Comment by matthewtsmith** [comment]
Released as part of 0.0.13
