### ISSUE TITLE
How to make MapActivity open as background of FlutterActivity?

### ISSUE THREAD

**Issue by lunvjp** [apptreesoftware/flutter_google_map_view#55]
Like this title, I just want to make my app have background of my Flutter's screen with Google Maps. So users can click some buttons in the top of that map.
Let me know if the information's clear or not. Thanks!

**Comment by matthewtsmith** [comment]
Not possible with this library, it works in full screen mode only. One option is to use a static map. Another option is to use our more flexible inline library based on leaflet: https://github.com/apptreesoftware/flutter_map
