### ISSUE TITLE
Use map satellite view

### ISSUE THREAD

**Issue by HelenGuov** [apptreesoftware/flutter_google_map_view#7]
I would like to use change the map view to Satellite. Is it possilbe to do that? 
Thanks.

**Comment by matthewtsmith** [comment]
Not currently but it would be fairly simple to add by adding support for specifying the MapType in the MapOptions. We can try to get to this in the near future, until then pull requests are welcome.

**Comment by HelenGuov** [comment]
How do I test the package locally?

**Comment by HelenGuov** [comment]
I am currently working on adding the ability to change `Map Type` and will do a pull request soon.

**Comment by matthewtsmith** [comment]
https://github.com/apptreesoftware/flutter_google_map_view/pull/9 has been merged.
