### ISSUE TITLE
Embedded Map View

### ISSUE THREAD

**Issue by CrazyStaff** [apptreesoftware/flutter_google_map_view#8]
Is it possible to embedd this map view as a stateless widget in my app 
without a new activity?

**Comment by matthewtsmith** [comment]
No, not currently. Inline native views are not currently supported in Flutter. They did just get support for inline video working but it doesn't quite have all the hooks we need to use for embedded maps.  You can track the flutter issue here: https://github.com/flutter/flutter/issues/73

**Comment by matthewtsmith** [comment]
We have started an experimental 100% dart/flutter implementation for inline maps [here](https://github.com/apptreesoftware/flutter_map). Closing this issue in favor of that development effort.
