### ISSUE TITLE
Configuration 'compile' in project ':map_view' is deprecated. Use 'implementation' instead.

### ISSUE THREAD

**Issue by ThePaceMaker** [apptreesoftware/flutter_google_map_view#86]
Running **flutter run** on Visual Studio code causes the following warning:

`Configuration 'compile' in project ':map_view' is deprecated. Use 'implementation' instead.`

However, it still runs/builds successfully (for now).

**Comment by matthewtsmith** [comment]
This has been fixed in 0.0.13

**Comment by ThePaceMaker** [comment]
Thanks for the heads up :thumbsup:
