### ISSUE TITLE
Show InfoWindow on Map tap?

### ISSUE THREAD

**Issue by rupert2133** [apptreesoftware/flutter_google_map_view#88]
Hi, I want to show the info window whenever you tap anywhere on the map. is it possible? 
I found a solution but the `marker.showInfoWindows();` doesn't exist in this project.
`Marker marker = myMap.addMarker(new MarkerOptions()`
                     `.position(latLng)`
                     `.title("Title")`
                   `.snippet("Snippet")`
                    `.icon(BitmapDescriptorFactory`
                     `.fromResource(R.drawable.marker)));`

`marker.showInfoWindow();`

right now I was able to show the info window by adding a marker whenever you tap but you need to tap again the marker to show the infowindow. I want to automatically show the infowindow whenever you tap anywhere on the map. Please help :(

**Comment by matthewtsmith** [comment]
This is not likely something we will get to. If you need something like this I suggest making a PR to support it.
